openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components:
  schemas:
    ArrayRestrictions:
      type: object
      required:
        - value
      properties:
        min:
          type: number
        max:
          type: number
        value:
          $ref: '#/components/schemas/IfcxValueDescription'
    DataType:
      type: string
      enum:
        - Real
        - Boolean
        - Integer
        - String
        - DateTime
        - Enum
        - Array
        - Object
        - Relation
    EnumRestrictions:
      type: object
      required:
        - options
      properties:
        options:
          type: array
          items:
            type: string
    IfcxFile:
      type: object
      required:
        - header
        - schemas
        - data
      properties:
        header:
          $ref: '#/components/schemas/IfcxHeader'
        schemas:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/IfcxSchema'
        data:
          type: array
          items:
            $ref: '#/components/schemas/IfcxNode'
    IfcxHeader:
      type: object
      required:
        - version
        - author
        - timestamp
        - defaultNode
      properties:
        version:
          type: string
        author:
          type: string
        timestamp:
          type: string
        defaultNode:
          $ref: '#/components/schemas/path'
    IfcxNode:
      type: object
      required:
        - name
        - children
        - inherits
        - attributes
      properties:
        name:
          $ref: '#/components/schemas/path'
        children:
          type: object
          additionalProperties:
            type: string
            nullable: true
        inherits:
          type: object
          additionalProperties:
            type: string
            nullable: true
        attributes:
          type: object
          additionalProperties: {}
    IfcxSchema:
      type: object
      required:
        - code
        - value
      properties:
        code:
          $ref: '#/components/schemas/code'
        uri:
          type: string
        value:
          $ref: '#/components/schemas/IfcxValueDescription'
    IfcxValueDescription:
      type: object
      required:
        - dataType
      properties:
        dataType:
          $ref: '#/components/schemas/DataType'
        measure:
          $ref: '#/components/schemas/Measure'
        enumRestrictions:
          $ref: '#/components/schemas/EnumRestrictions'
        arrayRestrictions:
          $ref: '#/components/schemas/ArrayRestrictions'
        objectRestrictions:
          $ref: '#/components/schemas/ObjectRestrictions'
        relationRestrictions:
          $ref: '#/components/schemas/RelationRestrictions'
    Measure:
      type: string
      enum:
        - IFCABSORBEDDOSEMEASURE
        - IFCACCELERATIONMEASURE
        - IFCACTIONREQUESTTYPEENUM
        - IFCACTIONSOURCETYPEENUM
        - IFCACTIONTYPEENUM
        - IFCACTUATORTYPEENUM
        - IFCADDRESSTYPEENUM
        - IFCAIRTERMINALBOXTYPEENUM
        - IFCAIRTERMINALTYPEENUM
        - IFCAIRTOAIRHEATRECOVERYTYPEENUM
        - IFCALARMTYPEENUM
        - IFCALIGNMENTCANTSEGMENTTYPEENUM
        - IFCALIGNMENTHORIZONTALSEGMENTTYPEENUM
        - IFCALIGNMENTTYPEENUM
        - IFCALIGNMENTVERTICALSEGMENTTYPEENUM
        - IFCAMOUNTOFSUBSTANCEMEASURE
        - IFCANALYSISMODELTYPEENUM
        - IFCANALYSISTHEORYTYPEENUM
        - IFCANGULARVELOCITYMEASURE
        - IFCANNOTATIONTYPEENUM
        - IFCAREADENSITYMEASURE
        - IFCAREAMEASURE
        - IFCARITHMETICOPERATORENUM
        - IFCASSEMBLYPLACEENUM
        - IFCAUDIOVISUALAPPLIANCETYPEENUM
        - IFCBEAMTYPEENUM
        - IFCBEARINGTYPEENUM
        - IFCBENCHMARKENUM
        - IFCBINARY
        - IFCBOILERTYPEENUM
        - IFCBOOLEAN
        - IFCBOXALIGNMENT
        - IFCBRIDGEPARTTYPEENUM
        - IFCBRIDGETYPEENUM
        - IFCBUILDINGELEMENTPARTTYPEENUM
        - IFCBUILDINGELEMENTPROXYTYPEENUM
        - IFCBUILDINGSYSTEMTYPEENUM
        - IFCBUILTSYSTEMTYPEENUM
        - IFCBURNERTYPEENUM
        - IFCCABLECARRIERFITTINGTYPEENUM
        - IFCCABLECARRIERSEGMENTTYPEENUM
        - IFCCABLEFITTINGTYPEENUM
        - IFCCABLESEGMENTTYPEENUM
        - IFCCAISSONFOUNDATIONTYPEENUM
        - IFCCARDINALPOINTREFERENCE
        - IFCCHANGEACTIONENUM
        - IFCCHILLERTYPEENUM
        - IFCCHIMNEYTYPEENUM
        - IFCCOILTYPEENUM
        - IFCCOLUMNTYPEENUM
        - IFCCOMMUNICATIONSAPPLIANCETYPEENUM
        - IFCCOMPLEXPROPERTYTEMPLATETYPEENUM
        - IFCCOMPRESSORTYPEENUM
        - IFCCONDENSERTYPEENUM
        - IFCCONNECTIONTYPEENUM
        - IFCCONSTRAINTENUM
        - IFCCONSTRUCTIONEQUIPMENTRESOURCETYPEENUM
        - IFCCONSTRUCTIONMATERIALRESOURCETYPEENUM
        - IFCCONSTRUCTIONPRODUCTRESOURCETYPEENUM
        - IFCCONTEXTDEPENDENTMEASURE
        - IFCCONTROLLERTYPEENUM
        - IFCCONVEYORSEGMENTTYPEENUM
        - IFCCOOLEDBEAMTYPEENUM
        - IFCCOOLINGTOWERTYPEENUM
        - IFCCOSTITEMTYPEENUM
        - IFCCOSTSCHEDULETYPEENUM
        - IFCCOUNTMEASURE
        - IFCCOURSETYPEENUM
        - IFCCOVERINGTYPEENUM
        - IFCCREWRESOURCETYPEENUM
        - IFCCURRENCYENUM
        - IFCCURTAINWALLTYPEENUM
        - IFCCURVATUREMEASURE
        - IFCCURVEINTERPOLATIONENUM
        - IFCDAMPERTYPEENUM
        - IFCDATAORIGINENUM
        - IFCDATE
        - IFCDATETIME
        - IFCDAYINMONTHNUMBER
        - IFCDAYINWEEKNUMBER
        - IFCDAYLIGHTSAVINGHOUR
        - IFCDERIVEDUNITENUM
        - IFCDESCRIPTIVEMEASURE
        - IFCDIMENSIONCOUNT
        - IFCDIRECTIONSENSEENUM
        - IFCDISCRETEACCESSORYTYPEENUM
        - IFCDISTRIBUTIONBOARDTYPEENUM
        - IFCDISTRIBUTIONCHAMBERELEMENTTYPEENUM
        - IFCDISTRIBUTIONPORTTYPEENUM
        - IFCDISTRIBUTIONSYSTEMENUM
        - IFCDOCUMENTCONFIDENTIALITYENUM
        - IFCDOCUMENTSTATUSENUM
        - IFCDOORPANELOPERATIONENUM
        - IFCDOORPANELPOSITIONENUM
        - IFCDOORSTYLECONSTRUCTIONENUM
        - IFCDOORSTYLEOPERATIONENUM
        - IFCDOORTYPEENUM
        - IFCDOORTYPEOPERATIONENUM
        - IFCDOSEEQUIVALENTMEASURE
        - IFCDUCTFITTINGTYPEENUM
        - IFCDUCTSEGMENTTYPEENUM
        - IFCDUCTSILENCERTYPEENUM
        - IFCDURATION
        - IFCDYNAMICVISCOSITYMEASURE
        - IFCEARTHWORKSCUTTYPEENUM
        - IFCEARTHWORKSFILLTYPEENUM
        - IFCELECTRICAPPLIANCETYPEENUM
        - IFCELECTRICCAPACITANCEMEASURE
        - IFCELECTRICCHARGEMEASURE
        - IFCELECTRICCONDUCTANCEMEASURE
        - IFCELECTRICCURRENTENUM
        - IFCELECTRICCURRENTMEASURE
        - IFCELECTRICDISTRIBUTIONBOARDTYPEENUM
        - IFCELECTRICDISTRIBUTIONPOINTFUNCTIONENUM
        - IFCELECTRICFLOWSTORAGEDEVICETYPEENUM
        - IFCELECTRICFLOWTREATMENTDEVICETYPEENUM
        - IFCELECTRICGENERATORTYPEENUM
        - IFCELECTRICHEATERTYPEENUM
        - IFCELECTRICMOTORTYPEENUM
        - IFCELECTRICRESISTANCEMEASURE
        - IFCELECTRICTIMECONTROLTYPEENUM
        - IFCELECTRICVOLTAGEMEASURE
        - IFCELEMENTASSEMBLYTYPEENUM
        - IFCELEMENTCOMPOSITIONENUM
        - IFCENERGYMEASURE
        - IFCENERGYSEQUENCEENUM
        - IFCENGINETYPEENUM
        - IFCENVIRONMENTALIMPACTCATEGORYENUM
        - IFCEVAPORATIVECOOLERTYPEENUM
        - IFCEVAPORATORTYPEENUM
        - IFCEVENTTRIGGERTYPEENUM
        - IFCEVENTTYPEENUM
        - IFCEXTERNALSPATIALELEMENTTYPEENUM
        - IFCFACILITYPARTCOMMONTYPEENUM
        - IFCFACILITYUSAGEENUM
        - IFCFANTYPEENUM
        - IFCFASTENERTYPEENUM
        - IFCFILTERTYPEENUM
        - IFCFIRESUPPRESSIONTERMINALTYPEENUM
        - IFCFLOWDIRECTIONENUM
        - IFCFLOWINSTRUMENTTYPEENUM
        - IFCFLOWMETERTYPEENUM
        - IFCFONTSTYLE
        - IFCFONTVARIANT
        - IFCFONTWEIGHT
        - IFCFOOTINGTYPEENUM
        - IFCFORCEMEASURE
        - IFCFREQUENCYMEASURE
        - IFCFURNITURETYPEENUM
        - IFCGASTERMINALTYPEENUM
        - IFCGEOGRAPHICELEMENTTYPEENUM
        - IFCGEOMETRICPROJECTIONENUM
        - IFCGEOTECHNICALSTRATUMTYPEENUM
        - IFCGLOBALLYUNIQUEID
        - IFCGLOBALORLOCALENUM
        - IFCGRIDTYPEENUM
        - IFCHEATEXCHANGERTYPEENUM
        - IFCHEATFLUXDENSITYMEASURE
        - IFCHEATINGVALUEMEASURE
        - IFCHOURINDAY
        - IFCHUMIDIFIERTYPEENUM
        - IFCIDENTIFIER
        - IFCILLUMINANCEMEASURE
        - IFCIMPACTPROTECTIONDEVICETYPEENUM
        - IFCINDUCTANCEMEASURE
        - IFCINTEGER
        - IFCINTEGERCOUNTRATEMEASURE
        - IFCINTERCEPTORTYPEENUM
        - IFCINTERNALOREXTERNALENUM
        - IFCINVENTORYTYPEENUM
        - IFCIONCONCENTRATIONMEASURE
        - IFCISOTHERMALMOISTURECAPACITYMEASURE
        - IFCJUNCTIONBOXTYPEENUM
        - IFCKERBTYPEENUM
        - IFCKINEMATICVISCOSITYMEASURE
        - IFCLABEL
        - IFCLABORRESOURCETYPEENUM
        - IFCLAMPTYPEENUM
        - IFCLANGUAGEID
        - IFCLAYERSETDIRECTIONENUM
        - IFCLENGTHMEASURE
        - IFCLIGHTDISTRIBUTIONCURVEENUM
        - IFCLIGHTEMISSIONSOURCEENUM
        - IFCLIGHTFIXTURETYPEENUM
        - IFCLINEARFORCEMEASURE
        - IFCLINEARMOMENTMEASURE
        - IFCLINEARSTIFFNESSMEASURE
        - IFCLINEARVELOCITYMEASURE
        - IFCLIQUIDTERMINALTYPEENUM
        - IFCLOADGROUPTYPEENUM
        - IFCLOGICAL
        - IFCLOGICALOPERATORENUM
        - IFCLUMINOUSFLUXMEASURE
        - IFCLUMINOUSINTENSITYDISTRIBUTIONMEASURE
        - IFCLUMINOUSINTENSITYMEASURE
        - IFCMAGNETICFLUXDENSITYMEASURE
        - IFCMAGNETICFLUXMEASURE
        - IFCMARINEFACILITYTYPEENUM
        - IFCMARINEPARTTYPEENUM
        - IFCMASSDENSITYMEASURE
        - IFCMASSFLOWRATEMEASURE
        - IFCMASSMEASURE
        - IFCMASSPERLENGTHMEASURE
        - IFCMECHANICALFASTENERTYPEENUM
        - IFCMEDICALDEVICETYPEENUM
        - IFCMEMBERTYPEENUM
        - IFCMINUTEINHOUR
        - IFCMOBILETELECOMMUNICATIONSAPPLIANCETYPEENUM
        - IFCMODULUSOFELASTICITYMEASURE
        - IFCMODULUSOFLINEARSUBGRADEREACTIONMEASURE
        - IFCMODULUSOFROTATIONALSUBGRADEREACTIONMEASURE
        - IFCMODULUSOFSUBGRADEREACTIONMEASURE
        - IFCMOISTUREDIFFUSIVITYMEASURE
        - IFCMOLECULARWEIGHTMEASURE
        - IFCMOMENTOFINERTIAMEASURE
        - IFCMONETARYMEASURE
        - IFCMONTHINYEARNUMBER
        - IFCMOORINGDEVICETYPEENUM
        - IFCMOTORCONNECTIONTYPEENUM
        - IFCNAVIGATIONELEMENTTYPEENUM
        - IFCNONNEGATIVELENGTHMEASURE
        - IFCNORMALISEDRATIOMEASURE
        - IFCNULLSTYLE
        - IFCNULLSTYLEENUM
        - IFCNUMERICMEASURE
        - IFCOBJECTIVEENUM
        - IFCOBJECTTYPEENUM
        - IFCOCCUPANTTYPEENUM
        - IFCOPENINGELEMENTTYPEENUM
        - IFCOUTLETTYPEENUM
        - IFCPARAMETERVALUE
        - IFCPAVEMENTTYPEENUM
        - IFCPERFORMANCEHISTORYTYPEENUM
        - IFCPERMEABLECOVERINGOPERATIONENUM
        - IFCPERMITTYPEENUM
        - IFCPHMEASURE
        - IFCPHYSICALORVIRTUALENUM
        - IFCPILECONSTRUCTIONENUM
        - IFCPILETYPEENUM
        - IFCPIPEFITTINGTYPEENUM
        - IFCPIPESEGMENTTYPEENUM
        - IFCPLANARFORCEMEASURE
        - IFCPLANEANGLEMEASURE
        - IFCPLATETYPEENUM
        - IFCPOSITIVEINTEGER
        - IFCPOSITIVELENGTHMEASURE
        - IFCPOSITIVEPLANEANGLEMEASURE
        - IFCPOSITIVERATIOMEASURE
        - IFCPOWERMEASURE
        - IFCPRESENTABLETEXT
        - IFCPRESSUREMEASURE
        - IFCPROCEDURETYPEENUM
        - IFCPROFILETYPEENUM
        - IFCPROJECTEDORTRUELENGTHENUM
        - IFCPROJECTIONELEMENTTYPEENUM
        - IFCPROJECTORDERRECORDTYPEENUM
        - IFCPROJECTORDERTYPEENUM
        - IFCPROPERTYSETTEMPLATETYPEENUM
        - IFCPROPERTYSOURCEENUM
        - IFCPROTECTIVEDEVICETRIPPINGUNITTYPEENUM
        - IFCPROTECTIVEDEVICETYPEENUM
        - IFCPUMPTYPEENUM
        - IFCRADIOACTIVITYMEASURE
        - IFCRAILINGTYPEENUM
        - IFCRAILTYPEENUM
        - IFCRAILWAYPARTTYPEENUM
        - IFCRAILWAYTYPEENUM
        - IFCRAMPFLIGHTTYPEENUM
        - IFCRAMPTYPEENUM
        - IFCRATIOMEASURE
        - IFCREAL
        - IFCRECURRENCETYPEENUM
        - IFCREFERENTTYPEENUM
        - IFCREFLECTANCEMETHODENUM
        - IFCREINFORCEDSOILTYPEENUM
        - IFCREINFORCINGBARROLEENUM
        - IFCREINFORCINGBARSURFACEENUM
        - IFCREINFORCINGBARTYPEENUM
        - IFCREINFORCINGMESHTYPEENUM
        - IFCRESOURCECONSUMPTIONENUM
        - IFCRIBPLATEDIRECTIONENUM
        - IFCROADPARTTYPEENUM
        - IFCROADTYPEENUM
        - IFCROLEENUM
        - IFCROOFTYPEENUM
        - IFCROTATIONALFREQUENCYMEASURE
        - IFCROTATIONALMASSMEASURE
        - IFCROTATIONALSTIFFNESSMEASURE
        - IFCSANITARYTERMINALTYPEENUM
        - IFCSECONDINMINUTE
        - IFCSECTIONALAREAINTEGRALMEASURE
        - IFCSECTIONMODULUSMEASURE
        - IFCSECTIONTYPEENUM
        - IFCSENSORTYPEENUM
        - IFCSEQUENCEENUM
        - IFCSERVICELIFEFACTORTYPEENUM
        - IFCSERVICELIFETYPEENUM
        - IFCSHADINGDEVICETYPEENUM
        - IFCSHEARMODULUSMEASURE
        - IFCSIGNALTYPEENUM
        - IFCSIGNTYPEENUM
        - IFCSIMPLEPROPERTYTEMPLATETYPEENUM
        - IFCSLABTYPEENUM
        - IFCSOLARDEVICETYPEENUM
        - IFCSOLIDANGLEMEASURE
        - IFCSOUNDPOWERLEVELMEASURE
        - IFCSOUNDPOWERMEASURE
        - IFCSOUNDPRESSURELEVELMEASURE
        - IFCSOUNDPRESSUREMEASURE
        - IFCSOUNDSCALEENUM
        - IFCSPACEHEATERTYPEENUM
        - IFCSPACETYPEENUM
        - IFCSPATIALZONETYPEENUM
        - IFCSPECIFICHEATCAPACITYMEASURE
        - IFCSPECULAREXPONENT
        - IFCSPECULARROUGHNESS
        - IFCSTACKTERMINALTYPEENUM
        - IFCSTAIRFLIGHTTYPEENUM
        - IFCSTAIRTYPEENUM
        - IFCSTATEENUM
        - IFCSTRIPPEDOPTIONAL
        - IFCSTRUCTURALCURVEACTIVITYTYPEENUM
        - IFCSTRUCTURALCURVEMEMBERTYPEENUM
        - IFCSTRUCTURALCURVETYPEENUM
        - IFCSTRUCTURALSURFACEACTIVITYTYPEENUM
        - IFCSTRUCTURALSURFACEMEMBERTYPEENUM
        - IFCSTRUCTURALSURFACETYPEENUM
        - IFCSUBCONTRACTRESOURCETYPEENUM
        - IFCSURFACEFEATURETYPEENUM
        - IFCSURFACETEXTUREENUM
        - IFCSWITCHINGDEVICETYPEENUM
        - IFCSYSTEMFURNITUREELEMENTTYPEENUM
        - IFCTANKTYPEENUM
        - IFCTASKDURATIONENUM
        - IFCTASKTYPEENUM
        - IFCTEMPERATUREGRADIENTMEASURE
        - IFCTEMPERATURERATEOFCHANGEMEASURE
        - IFCTENDONANCHORTYPEENUM
        - IFCTENDONCONDUITTYPEENUM
        - IFCTENDONTYPEENUM
        - IFCTEXT
        - IFCTEXTALIGNMENT
        - IFCTEXTDECORATION
        - IFCTEXTFONTNAME
        - IFCTEXTTRANSFORMATION
        - IFCTHERMALADMITTANCEMEASURE
        - IFCTHERMALCONDUCTIVITYMEASURE
        - IFCTHERMALEXPANSIONCOEFFICIENTMEASURE
        - IFCTHERMALLOADSOURCEENUM
        - IFCTHERMALLOADTYPEENUM
        - IFCTHERMALRESISTANCEMEASURE
        - IFCTHERMALTRANSMITTANCEMEASURE
        - IFCTHERMODYNAMICTEMPERATUREMEASURE
        - IFCTIME
        - IFCTIMEMEASURE
        - IFCTIMESERIESDATATYPEENUM
        - IFCTIMESERIESSCHEDULETYPEENUM
        - IFCTIMESTAMP
        - IFCTORQUEMEASURE
        - IFCTRACKELEMENTTYPEENUM
        - IFCTRANSFORMERTYPEENUM
        - IFCTRANSPORTELEMENTTYPEENUM
        - IFCTUBEBUNDLETYPEENUM
        - IFCUNITARYCONTROLELEMENTTYPEENUM
        - IFCUNITARYEQUIPMENTTYPEENUM
        - IFCUNITENUM
        - IFCURIREFERENCE
        - IFCVALVETYPEENUM
        - IFCVAPORPERMEABILITYMEASURE
        - IFCVEHICLETYPEENUM
        - IFCVIBRATIONDAMPERTYPEENUM
        - IFCVIBRATIONISOLATORTYPEENUM
        - IFCVIRTUALELEMENTTYPEENUM
        - IFCVOIDINGFEATURETYPEENUM
        - IFCVOLUMEMEASURE
        - IFCVOLUMETRICFLOWRATEMEASURE
        - IFCWALLTYPEENUM
        - IFCWARPINGCONSTANTMEASURE
        - IFCWARPINGMOMENTMEASURE
        - IFCWASTETERMINALTYPEENUM
        - IFCWELLKNOWNTEXTLITERAL
        - IFCWINDOWPANELOPERATIONENUM
        - IFCWINDOWPANELPOSITIONENUM
        - IFCWINDOWSTYLECONSTRUCTIONENUM
        - IFCWINDOWSTYLEOPERATIONENUM
        - IFCWINDOWTYPEENUM
        - IFCWINDOWTYPEPARTITIONINGENUM
        - IFCWORKCALENDARTYPEENUM
        - IFCWORKCONTROLTYPEENUM
        - IFCWORKPLANTYPEENUM
        - IFCWORKSCHEDULETYPEENUM
        - IFCYEARNUMBER
    ObjectRestrictions:
      type: object
      required:
        - values
      properties:
        values:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/IfcxValueDescription'
    RelationRestrictions:
      type: object
      required:
        - type
      properties:
        type:
          type: string
    code:
      type: string
      pattern: </[A-Za-z0-9]+>
    path:
      type: string
      pattern: </[A-Za-z0-9_/.:]+>
