[project]
name = "ifc5-development"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.18.0",
    "geopandas>=1.0.1",
    "jupyter>=1.1.1",
    "mapclassify>=2.8.1",
    "matplotlib>=3.9.3",
]
